### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by TheNextLevel** [ethereum-alarm-clock/cli#136]
Running the latest CLI with local geth on Ubuntu sporadically shows some errors I do not know what to do with it:

(node:20910) UnhandledPromiseRejectionWarning: Error: [0x64aac3e55c93ae66a76e73ceaf96ff33d0ab01c0] Unrecognized temporal unit: 0
    at TxRequest.now (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:96:11)
    at TxRequest.inFreezePeriod (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:113:28)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:74:33)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.freezePeriod (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:73:16)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:155:36)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.route (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:152:16)
    at TimeNodeScanner.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Scanner/CacheScanner.js:28:29)
    at Generator.next (<anonymous>)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20910) UnhandledPromiseRejectionWarning: Error: [0x64aac3e55c93ae66a76e73ceaf96ff33d0ab01c0] Unrecognized temporal unit: 0
    at TxRequest.now (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:96:11)
    at TxRequest.inFreezePeriod (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:113:28)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:74:33)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.freezePeriod (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:73:16)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:155:36)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.route (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:152:16)
    at TimeNodeScanner.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Scanner/CacheScanner.js:28:29)
    at Generator.next (<anonymous>)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:20910) UnhandledPromiseRejectionWarning: Error: [0x64aac3e55c93ae66a76e73ceaf96ff33d0ab01c0] Unrecognized temporal unit: 0
    at TxRequest.now (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:96:11)
    at TxRequest.inFreezePeriod (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:113:28)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:74:33)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.freezePeriod (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:73:16)
    at Router.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:155:36)
    at Generator.next (<anonymous>)
    at /home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:3:12)
    at Router.route (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Router/Router.js:152:16)
    at TimeNodeScanner.<anonymous> (/home/master/eac/cli-master/node_modules/@ethereum-alarm-clock/timenode-core/built/src/Scanner/CacheScanner.js:28:29)
    at Generator.next (<anonymous>)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:20910) UnhandledPromiseRejectionWarning: Error: no suitable peers available
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at Object.<anonymous> (/home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:121:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:98:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/master/eac/cli-master/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.emit (domain.js:421:20)
    at WebSocketConnection.processFrame (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:20910) UnhandledPromiseRejectionWarning: Error: no suitable peers available
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at Object.<anonymous> (/home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:121:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:98:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/master/eac/cli-master/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.emit (domain.js:421:20)
    at WebSocketConnection.processFrame (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:20910) UnhandledPromiseRejectionWarning: Error: no suitable peers available
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at Object.<anonymous> (/home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:121:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:98:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/master/eac/cli-master/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.emit (domain.js:421:20)
    at WebSocketConnection.processFrame (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:20910) UnhandledPromiseRejectionWarning: Error: no suitable peers available
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at Object.<anonymous> (/home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:121:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/src/index.js:98:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/master/eac/cli-master/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:180:13)
    at WebSocketConnection.emit (domain.js:421:20)
    at WebSocketConnection.processFrame (/home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/master/eac/cli-master/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)

```

**Comment by lsaether** [comment]
```
[0x64aac3e55c93ae66a76e73ceaf96ff33d0ab01c0] Unrecognized temporal unit: 0
at TxRequest.now (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:96:11)
at TxRequest.inFreezePeriod (/home/master/eac/cli-master/node_modules/eac.js-lib/lib/txRequest/txRequest.js:113:28)
```

Already fixed this in one instance in ethereum-alarm-clock/eac.js-lib#46 but it looks like I missed it here in the `TxRequest.inFreezePeriod()`. Fix incoming ASAP and included in Friday's release.

```
UnhandledPromiseRejectionWarning: Error: no suitable peers available
```

This looks like to me that you are having a networking problem where your node cannot connect to peers. What is your network environment like? Can you see if your node was disconnecting from peers?

**Comment by TheNextLevel** [comment]
The peer error may rely to the geth,  which is running in light mode. since te is no timestamp in the error messages, I cannot crosscheck the geth log.

**Comment by lsaether** [comment]
@TheNextLevel The first error of unrecognized temporal unit is patched by ethereum-alarm-clock/eac.js-lib#51

The other error is likely due to your Geth node. We should have timestamps in the logs (it keeps getting added in and taken out apparently) so I'll make sure it's added back in again.

Closing this as resolved.
