### ISSUE TITLE
Cannot send .testTx

### ISSUE THREAD

**Issue by TheNextLevel** [ethereum-alarm-clock/cli#64]
When I try to send a test transaction with .testTX, the following message appears and hangs:

```
⠋ Sending test transaction to network...(node:10685) UnhandledPromiseRejectionWarning: ReferenceError: conf is not defined
    at REPLServer.action (/home/master/eac/cli-master/src/TimeNode/repl.js:136:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:10685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using Version 4.2.5
npm version 6.2.0
Ubuntu 17.10

**Comment by lsaether** [comment]
Closed by #76
