### ISSUE TITLE
Negative earnings

### ISSUE THREAD

**Issue by TheNextLevel** [ethereum-alarm-clock/cli#65]
After 3 executions, the timenode account balance is less than before:

```
>> .getBalance
0x26bf5bb9465538ea9549111c5372d1911187e644 | Balance: 1.004557496
>> .getStats
0x26bf5bb9465538ea9549111c5372d1911187e644 | Executed: 0 | Claimed: 0 (ON) | Ether gain: 0.000000 (0.000000 - 0.000000)

[info] [0x8615fb35e0f6e0a5cdd9060760a58a477e1f4a3d] Discovered
[info] [0x8615fb35e0f6e0a5cdd9060760a58a477e1f4a3d] Inputting to cache
[info] 0x8615fb35e0f6e0a5cdd9060760a58a477e1f4a3d claimed
[info] [0x4e78e9853262d0b8b166b0e5fe1336ebb03bd94e] Discovered
[info] [0x4e78e9853262d0b8b166b0e5fe1336ebb03bd94e] Inputting to cache
[info] [0xf3a25610d58d5e4a1df81ae0e840c3377ab91071] Discovered
[info] [0xf3a25610d58d5e4a1df81ae0e840c3377ab91071] Inputting to cache
[info] 0xf3a25610d58d5e4a1df81ae0e840c3377ab91071 claimed
[info] 0x8615fb35e0f6e0a5cdd9060760a58a477e1f4a3d executed
[info] [0x8615fb35e0f6e0a5cdd9060760a58a477e1f4a3d] Finished. Deleting from cache...
[info] 0xf3a25610d58d5e4a1df81ae0e840c3377ab91071 executed
[info] [0xf3a25610d58d5e4a1df81ae0e840c3377ab91071] Finished. Deleting from cache...

>> .getBalance
0x26bf5bb9465538ea9549111c5372d1911187e644 | Balance: 1.001965026
>> .getStats
0x26bf5bb9465538ea9549111c5372d1911187e644 | Executed: 3 | Claimed: 2 (ON) | Ether gain: 0.001726 (0.003453 - 0.001727)
```

And always repeating  in the log:
`(node:10836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)`

**Comment by adibas03** [comment]
The lower balance is an indication of the claimed transactions which you can see from the `.getStats`
Once the claimed transactions are executed, you would get a claim refund plus the bounty.
We are aware of the error log and are looking into it, presently.

**Comment by TheNextLevel** [comment]
If so, a command like .getClaims would be nice to see what TXs for when is claimed. To plan maintenance times, we need a way to check if it is safe to stop the timenode  at a given time. Or we need a way to "declaim".

**Comment by adibas03** [comment]
That is already implemented in Dapp, develop branch and would also be implemented in the cli
@Kuzirashi

**Comment by Kuzirashi** [comment]
That's interesting idea, seems like it should be straightforward to implement `.getClaims` in CLI, since API for that is already present in the timenode-core library. Thanks @TheNextLevel for suggestion.

**Comment by TheNextLevel** [comment]
```
>> .getBalance
0x26bf5bb9465538ea9549111c5372d1911187e644 | Balance: 1.001965026
>> .getStats
0x26bf5bb9465538ea9549111c5372d1911187e644 | Executed: 3 | Claimed: 2 (ON) | Ether gain: 0.001726 (0.003453 - 0.001727)

(node:10836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 375)

>> .getStats
0x26bf5bb9465538ea9549111c5372d1911187e644 | Executed: 28 | Claimed: 27 (ON) | Ether gain: 0.053611 (0.094510 - 0.040898)
>> .getBalance
0x26bf5bb9465538ea9549111c5372d1911187e644 | Balance: 0.9941712626

```

After 23 executions, balance still get lower and lower. I'm scared to use a TN in main-net  ^^

**Comment by adibas03** [comment]
@TheNextLevel From that you presently have `0.040898 ETH` in claimed transactions.
If you add that to your balance: `1.0351 ETH`, which is profit.
Though you need to keep the node running to ensure you execute the claimed transactions to get back your sake and get your profit.

**Comment by lsaether** [comment]
@TheNextLevel 
Could you post the full unhandled Promise error?

**Comment by Kuzirashi** [comment]
@TheNextLevel 

Could you as well let us know which provider are you using? Are you using default one, or local Parity or Geth node?

**Comment by TheNextLevel** [comment]
@lsaether It is always the same:
```
(node:10836) UnhandledPromiseRejectionWarning: Error: Invalid params: invalid type: null, expected a hex-encoded or decimal index.
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/master/eac/cli-master/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:10836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 374)
(node:10836) UnhandledPromiseRejectionWarning: Error: Invalid params: invalid type: null, expected a hex-encoded or decimal index.
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/master/eac/cli-master/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:10836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 375)

```

**Comment by TheNextLevel** [comment]
@Kuzirashi 
--provider http://localhost:8180

I'm using Parity v1.10.6-20180605 stable

local on the same machine

**Comment by lsaether** [comment]
@TheNextLevel 
We are trying to reproduce your error and fix it.

**Comment by Kuzirashi** [comment]
We've introduced `.getClaimed` command, which shows claimed, but not executed transactions logged during TimeNode run-time in PR #69.

cc @TheNextLevel
