### ISSUE TITLE
UnhandledPromiseRejectionWarning every 20 minutes

### ISSUE THREAD

**Issue by TheNextLevel** [ethereum-alarm-clock/cli#78]
Version 4.2.6

There is still an error message "UnhandledPromiseRejectionWarning" every ~20 minutes 

```

(node:29265) UnhandledPromiseRejectionWarning: Error: Invalid params: invalid type: null, expected a hex-encoded or decimal index.
    at Object.InvalidResponse (/home/master/eac/cli-master/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/master/eac/cli-master/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/master/eac/cli-master/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/master/eac/cli-master/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:29265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)

```

And the log has still no timestamp :)

```
[info] [0x0b7b10754a131617960a86ea05319e6eb0252a12] Discovered
[info] [0x0b7b10754a131617960a86ea05319e6eb0252a12] Inputting to cache
[info] [0x5fb4ba20174928a29ed8de1ed5e368e87d08ae3c] Discovered
[info] [0x5fb4ba20174928a29ed8de1ed5e368e87d08ae3c] Inputting to cache
[info] 0xa9450974c906604950fcccdcc7516d30af92f4e5 claimed
[info] 0x5fb4ba20174928a29ed8de1ed5e368e87d08ae3c claimed
[info] 0xa9450974c906604950fcccdcc7516d30af92f4e5 executed
[info] [0xa9450974c906604950fcccdcc7516d30af92f4e5] Finished. Deleting from cache...
[info] [0x0b7b10754a131617960a86ea05319e6eb0252a12] Finished. Deleting from cache...
[info] 0x5fb4ba20174928a29ed8de1ed5e368e87d08ae3c executed
[info] [0x5fb4ba20174928a29ed8de1ed5e368e87d08ae3c] Finished. Deleting from cache...
```

**Comment by kosecki123** [comment]
Thanks for the report. Should be fixed in the next release. Underlying libraries has been updated with new code to handle that issue:

https://github.com/ethereum-alarm-clock/timenode-core/pull/169
https://github.com/ethereum-alarm-clock/timenode-core/pull/173

**Comment by lsaether** [comment]
Looks like the timestamps were taken out of the logger at some point during refactoring. Will need to push a PR to re-add them before this issue is closed.

**Comment by kosecki123** [comment]
Logs improvements (including timestamps) https://github.com/ethereum-alarm-clock/timenode-core/pull/182

**Comment by lsaether** [comment]
@kosecki123 I see now that we're using a different Logger implementation in the CLI from the default logger in order to log to file. I guess the best thing to do is implement a `FileLogger` based on the default logger in timenode-core.
